services:
  neo4j:
    image: neo4j:latest
    container_name: andres-202010495
    restart: always
    environment:
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"
      NEO4J_dbms_connector_bolt_advertised_address: "neo4j:7687"
      NEO4J_dbms_connector_bolt_tls_level: "DISABLED"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - ./import:/import

  backend:
    build: ./backend
    container_name: express_backend
    restart: always
    depends_on:
      - neo4j
    env_file:
      - .env
    ports:
      - "${EXPRESS_PORT:-3000}:3000"

volumes:
  neo4j_data:
    driver: local
