services:
  neo4j:
    image: neo4j:latest
    container_name: andres-202010495_neo4j
    restart: always
    environment:
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PASSWORD}"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - ./import:/import
    networks:
      - my_app_network

  backend:
    build: ./backend
    container_name: express_backend
    restart: always
    depends_on:
      - neo4j
    env_file:
      - .env
    networks:
      - my_app_network
    ports:
      - "${EXPRESS_PORT:-3000}:3000"

volumes:
  neo4j_data:
    driver: local

networks:
  my_app_network:
    driver: bridge
